settings:
  analysis:
    filter:
      edge_ngram:
        type:     edgeNGram
        min_gram: 1
        max_gram: 20
    analyzer:
      edge_ngram:
        type: custom
        tokenizer: standard
        filter: [
          "lowercase",
          "edge_ngram"
        ]
mappings:
  default:
    dynamic_templates:
      - template:
          match:               "*"
          match_mapping_type:  string
          mapping:
            type:            string
            index_analyzer:  edge_ngram
            search_analyzer: standard
